### ISSUE TITLE
General: Lag when selecting codes

### ISSUE THREAD

**Issue by ink-monkey** [rpgauthier/ComputationalThematicAnalysisToolkit#36]
Whenever I code for too long the toolkit starts to lag. The lag happens when I try to select new codes for a document, instead of being instantaneous the little loading circle appears instead of the mouse and it takes from 1-10 seconds for the click to happen. Here is how it happens, and I use and average of 3 codes per document:
1. Coding the first document. I open them on the data collection module by double clicking. When the window opens I select the codes I want and then close the window by pressing 'x'
2. Around 10-12 documents later the lag begins
3. Around 14-15 documents there is a 2-3 second lag before each action
4. Around document 20 the lag is 3-4 seconds long
5. 30th document, 5 second lag
6. 35th document, 6 second lag
7. It increases in increments until the 50th document, when the lag is around 10-11 seconds.
8. Around then I save my progress and close the toolkit
9. Wait for around 1 minute and then open it again
10. Load the last save and the lag is gone

I tried to just open the windows without coding anything and the same problem happened again. This time what I did was:
1. Open toolkit and load a file.
2. Open 50 consecutive windows on the data collection module, without selecting a single code.
3. When I tried to code the last opened window the lag was there and it was taking me around 10-11 seconds to do anything.

**Comment by rpgauthier** [comment]
Issue recreated and debug + memory monitoring identified issue. Initial fix created and undergoing testing to verify issue has been resolved.

**Comment by rpgauthier** [comment]
fix appears to be working on windows
